# NumPy Arrays Generation

In [1]:
import numpy as np

---

### From Python List

In [2]:
my_list = [1, 2, 3]
type(my_list)

list

In [3]:
my_array = np.array(mylist)
type(my_array)

numpy.ndarray

In [4]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---

### By method

**np.arange**

In [15]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1, 10, 1).reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

**np.zeros**

In [17]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros(10).reshape(2, -1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**np.ones**

In [20]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones(10).reshape(2, -1)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**np.linspace**

In [24]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.linspace(0, 56, 57)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56.])

**np.eye**

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### generate random data

**np.random.rand**
<br>0.0 - 1.0

In [28]:
# random number
np.random.rand()

0.8818936646437058

In [71]:
# random number in an array
np.random.rand(1)

array([0.53533556])

In [30]:
np.random.rand(10)

array([0.09894578, 0.75712331, 0.47486185, 0.03641586, 0.16494396,
       0.68126045, 0.9298194 , 0.11401147, 0.06050065, 0.94972933])

In [32]:
np.random.rand(5, 2, 4)

array([[[0.22299129, 0.85340386, 0.83026485, 0.39523093],
        [0.25275947, 0.13898381, 0.30541335, 0.00711004]],

       [[0.49684989, 0.08755313, 0.72955308, 0.07379463],
        [0.185631  , 0.66346048, 0.81648794, 0.10667926]],

       [[0.08768039, 0.15503308, 0.72178282, 0.27706982],
        [0.83640873, 0.83747544, 0.00871403, 0.07718131]],

       [[0.17241289, 0.25112631, 0.46748832, 0.38162344],
        [0.097728  , 0.82681404, 0.49538227, 0.20660784]],

       [[0.75612304, 0.18499306, 0.22584284, 0.91347911],
        [0.78117557, 0.91295143, 0.01427241, 0.38838001]]])

In [35]:
np.random.rand(9).reshape(3, -1)

array([[0.2314067 , 0.51263626, 0.43200571],
       [0.15239734, 0.37836496, 0.48653114],
       [0.34526404, 0.28275484, 0.5717628 ]])

**np.random.randn**<br>
-> random samples from normal distribution

In [36]:
np.random.randn()

0.3108141885262016

In [37]:
np.random.randn(10)

array([-0.84816218, -0.85967038, -0.89010064, -2.51622359, -1.60583403,
       -1.0235113 ,  1.66608892,  0.09055755,  0.34214182,  0.49071774])

In [39]:
np.random.randn(2, 5)

array([[-1.20268292,  0.00885515, -0.89050708, -1.2587969 ,  0.55518338],
       [-0.25426748,  0.18888011, -0.03067607, -0.76059677, -0.75556456]])

**np.random.randint**

In [40]:
np.random.randint(0, 10, 1)

array([5])

In [43]:
np.random.randint(0, 1, (5, 5))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [54]:
np.random.seed(42)
np.random.randint(0, 1000, 4)

array([102, 435, 860, 270])

In [48]:
np.random.randint(0, 1000, 4)

array([614, 121, 466, 214])

---

### more interesting methods

**reshape**

as method call:

In [56]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.arange(1, 10).reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.arange(1, 10).reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

or as function call:

In [60]:
np.reshape(np.arange(1,10), (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**argmin**<br>
-> get index of min

In [62]:
arr = np.random.randint(-100000, 100000, 1000)

In [63]:
arr.min()

-99596

In [64]:
arr.argmin()

817

In [65]:
arr[arr.argmin()]

-99596

**argmax**<br>
-> get index of max

In [66]:
arr.max()

99938

In [67]:
arr.argmax()

744

In [68]:
arr[arr.argmax()]

99938

**properties**

In [69]:
arr.dtype

dtype('int32')

In [70]:
arr.shape

(1000,)