# Slicing and Indexing Numpy Arrays

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**indexing**

In [4]:
arr[0]

0

In [5]:
arr[-1]

99

In [18]:
np.arange(1, 10).reshape(3,3)[0][1]

2

**slicing**

In [6]:
arr[94:]

array([94, 95, 96, 97, 98, 99])

In [10]:
arr[-6:]

array([94, 95, 96, 97, 98, 99])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
arr[:5] = -999
arr

array([-999, -999, -999, -999, -999,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99])

**slicing with 2D numpy arrays**

In [24]:
arr = np.arange(1, 10).reshape(3, -1)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
arr[1:, 1:]

array([[5, 6],
       [8, 9]])

In [27]:
arr[1:][1:]

array([[7, 8, 9]])

**copying an slice of an numpy array**

In [ ]:
# reset
arr = np.arange(0, 100)
arr

In [13]:
slice_arr = arr[3:66:3]
slice_arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63])

In [14]:
slice_arr[:] = -999
slice_arr

array([-999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999])

In [15]:
arr

array([   0,    1,    2, -999,    4,    5, -999,    7,    8, -999,   10,
         11, -999,   13,   14, -999,   16,   17, -999,   19,   20, -999,
         22,   23, -999,   25,   26, -999,   28,   29, -999,   31,   32,
       -999,   34,   35, -999,   37,   38, -999,   40,   41, -999,   43,
         44, -999,   46,   47, -999,   49,   50, -999,   52,   53, -999,
         55,   56, -999,   58,   59, -999,   61,   62, -999,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99])

In [19]:
# reset
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**use copy method**

In [20]:
slice_copy = arr[3:66:3].copy()
slice_copy

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63])

In [21]:
slice_arr[:] = -999
slice_arr

array([-999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999])

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**bool mask**

In [28]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
mask = (arr % 3 == 0)
mask

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True])

In [30]:
arr[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
arr[arr < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])