# NumPy Advanced Stuff

In [1]:
import numpy as np

In [7]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr2d = np.arange(1, 101).reshape(10, -1)
arr2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

**Array Operations**

In [8]:
arr + 5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [10]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

handle of zero error:

In [12]:
arr / arr

<ipython-input-12-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
# normal python throws an exception
try:
    1 / 0
except Exception as e:
    print(e)

division by zero


In [23]:
1 / arr

<ipython-input-23-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

**apply method**

In [25]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [27]:
np.log(arr)

<ipython-input-27-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

**methods for statistic**

In [28]:
arr.sum()

45

In [29]:
arr.mean()

4.5

In [31]:
arr.max()

9

In [32]:
arr.var()

8.25

In [33]:
arr.std()

2.8722813232690143

In [36]:
arr2d.shape

(10, 10)

In [37]:
# axis 1 means columns
# perform the sum across the columns, which results in the sum of the rows
arr2d.sum(axis=1)

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [38]:
# axis 0 means rows
# perform the sum across the rows, which results in the sum of the columns
arr2d.sum(axis=0)

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

**value to other value -> nice trick**

using pandas + numpy -> only with numpy should also work

In [ ]:
conditions = [(df.eruptions < 3.5), (df.eruptions >= 3.5)]
values = ['short', 'long']
df["duration"] = np.select(conditions, values)